### ISSUE TITLE
About the dataset.

### ISSUE THREAD

**Issue by aaa1999** [shijiansj/DeepCatra#2]
Please I want to know how I should put the datasets in the correct directory?Would you please give a some instructions about it?Thank you a lot.

**Comment by shijiansj** [comment]
We upload all the features of the whole dataset in the BaiduNetdisk. Therefore, if you want use the dataset, you need first split the features into benign and malware according to the hash list file in DeepCatra/Dataset/.
Finally you should put the dataset like this，which can be the input of the code：
![image](https://user-images.githubusercontent.com/78128072/176075385-718631ee-bafb-4f99-8b19-0164966780c8.png)
